### ISSUE TITLE
the New Arrivals Page still show mock data after modified the /newproducts entry

### ISSUE THREAD

**Issue by yul88** [GoogleCloudPlatform/cymbal-superstore#7]
Cloud Run failed to update to new version, due to wrong parameter settings.

Debug with curl, which shows that cloud run has not been updated.
<img width="811" alt="Screenshot 2024-01-08 at 22 00 58" src="https://github.com/GoogleCloudPlatform/cymbal-superstore/assets/65400231/cd18ca0f-cd96-495f-befa-fc66c9055a4e">

Try to manually update cloud run and failed due to timeout settings
<img width="1204" alt="Screenshot 2024-01-08 at 22 11 58" src="https://github.com/GoogleCloudPlatform/cymbal-superstore/assets/65400231/d82c1d3d-212c-4767-a761-9a2e49ab47bb">

Fix: set timeout_seconds to be less than period_seconds, in main.tf
<img width="296" alt="Screenshot 2024-01-08 at 22 34 42" src="https://github.com/GoogleCloudPlatform/cymbal-superstore/assets/65400231/b94ec09e-cb10-4351-b30c-7fbc1c556d04">

**Comment by klair** [comment]
Try adding the "Cloud Run Developer" role to your service account for Cloud Run, that should enable you to deploy new revisions via Terraform. I ended up with 3 roles on the service account, "Cloud Datastore Owner", "Cloud Run Invoker" & "Cloud Run Developer".

**Comment by darylducharme** [comment]
This was fixed with https://github.com/GoogleCloudPlatform/cymbal-superstore/pull/8
